### ISSUE TITLE
send_email_out cannot find `mailsend`

### ISSUE THREAD

**Issue by jonspring** [rich-iannone/blastula#30] opened 2019-02-24 22:28 UTC
Using Windows system through gmail. I can see the `.bls_smtp_gmail_com` and `sendmail` files in my home directory, but when I run

    send_email_out(
      message = email_object,
      from = "<myaccount>@gmail.com",
      to = "<email_destination>",
      subject = "Testing.",
      creds_file = "~/.e_creds")

I get:

    Error in system(command = command, intern = TRUE) : 'C:/<my home dir>/R/mailsend' not found

**Comment by jdbarillas** [comment] 2019-02-25 00:16
This might be a duplicate of #10 , try the answer given there.

**Comment by jonspring** [comment] 2019-02-25 01:17
Thanks for the tip. I installed mailsend.exe to the working directory and it seemed to process, but I haven't seen the email go through yet -- not in my gmail account's "send" folder, nor in the destination email. Here's the message I got:

`running command 'C:/<MY_DIR>/mailsend -from "<MY EMAIL>@gmail.com" -name "<MY EMAIL@gmail.com" -t "<DESTINATION EMAIL>" +cc +bc -sub "Testing." -ssl   -smtp smtp.gmail.com -port 465 -auth -user <MY EMAIL@GMAIL> -pass "<MY PASS>"  -mime-type "text/html" -enc-type "us-ascii" -disposition "inline" -attach "message_inlined.html" ' had status 1[1] TRUE`

**Comment by jdbarillas** [comment] 2019-02-25 02:45
Hmm, if you're using Gmail, have you changed your account settings? I saw this in the README:

>One additional note about using Gmail to send out email: you must first change account settings to let less secure apps use your account. Details on how to make this account-level change can be found in this [support document](https://support.google.com/accounts/answer/6010255).

**Comment by jonspring** [comment] 2019-02-25 03:37
Thanks again, that was it. Email sent after updating google settings.

**Closed** 2019-02-25 04:48 UTC
