### ISSUE TITLE
Inline ggplot not displayed in gmail client

### ISSUE THREAD

**Issue by pzprado** [rich-iannone/blastula#87] opened 2019-10-17 03:27 UTC
Inline ggplot works fine with mobile app (online tested Mail.app in iOS)

However, it doesn't display in the gmail or hotmail web clients.

Using 
```
compose_mail(
body = "Here's the plot below:
{add_ggplot(plot_object = plot, width = 5, height = 3)}

Cheers"
)
```

**Comment by bennlich** [comment] 2019-10-23 23:01
This is probably not a bug in blastula. It just reflects how different e-mail clients behave very differently. AFAIK the only way to reliably get an image to show up in the body of an e-mail is to reference it with an external URL (e.g. with https://rich-iannone.github.io/blastula/reference/add_imgur_image.html).

**Comment by rich-iannone** [comment] 2019-10-23 23:45
@pzprado Sorry I didn't reply before but @bennlich is correct. It seems that `mailsend-go`, while easier to install for everybody on different platforms compared to `mailsend`, is lacking an option to provide a `content-id` value.

I filed the issue https://github.com/muquit/mailsend-go/issues/3 but haven't yet gotten a response. This was possible in `mailsend` but seemingly not (unless I missed something crucial) in `mailsend-go`. As this is probably the single biggest issue with this package, I'm am currently looking for a solution. In the meantime, I'm going to advise users that embedded images do not work with `smtp_send()` (they *do* work in RStudio Connect, because there is a solution in place for this). The way to communicate this will be through a warning when embedding images and a limitations section in the README.

**Comment by rich-iannone** [comment] 2019-10-30 00:10
@pzprado @bennlich We are onto a solution that doesn't involve `mailsend-go` at all (instead using the **curl** R package). This approach—where we create the MIME message ourselves—is working out quite well. If you'd like to test it out, you can use:

```r
devtools::install_github("rich-iannone/blastula@remove-glue-inputs")
```

and the revised way of generating an email:

```r

plot_obj <- add_ggplot(plot_object = plot, width = 5, height = 3)

compose_email(
  body = md(c(
    "Here's the plot below:
    ",
    plot_obj,
    "Cheers"
  )
  )
)
```

It might take a few more days until this is merged to master but the new functionality can be tested now.

**Comment by rich-iannone** [comment] 2019-11-06 17:12
The changes mentioned here are now merged in `master`. Closing the issue.

**Closed by rich-iannone** 2019-11-06 17:12 UTC
Labels: Type: ⁇ Question

**Comment by nalsha** [comment] 2019-11-07 07:53
> @pzprado @bennlich We are onto a solution that doesn't involve `mailsend-go` at all (instead using the **curl** R package). This approach—where we create the MIME message ourselves—is working out quite well. If you'd like to test it out, you can use:
> 
> ```r
> devtools::install_github("rich-iannone/blastula@remove-glue-inputs")
> ```
> 
> and the revised way of generating an email:
> 
> ```r
> plot_obj <- add_ggplot(plot_object = plot, width = 5, height = 3)
> 
> compose_email(
>   body = md(c(
>     "Here's the plot below:
>     ",
>     plot_obj,
>     "Cheers"
>   )
>   )
> )
> ```
> 
> It might take a few more days until this is merged to master but the new functionality can be tested now.

I am getting the following error when installing 
devtools::install_github("rich-iannone/blastula@remove-glue-inputs")

Error - 
Downloading GitHub repo rich-iannone/blastula@remove-glue-inputs
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/rich-iannone/blastula/tarball/remove-glue-inputs'

Please suggest
