### ISSUE TITLE
CSS not rendering properly on Outlook

### ISSUE THREAD

**Issue by kaushiklakshman** [rich-iannone/blastula#93] opened 2019-10-30 06:14 UTC
Hi, 

Thanks very much for resolving #91. I installed the package as per your comments on #87 and it works perfectly. I am able to send emails but am now faced a different problem. 

I'm doing nothing outside the examples provided 

```
library(tidyverse)
library(blastula)

test_message <- prepare_test_message()

test_message %>%
  smtp_send(
    to = "me@myorg.com.au",
    from = "me@myorg.com.au",
    subject = "Test Message",
    credentials = creds(host = "mail.myorg.com.au",
                        port = 25, 
                        use_ssl = FALSE)
  )
```

The preview in Rstudio looks perfectly fine, but when I actually send the email it ends up not rendering some CSS and looks really off. 

I'm attaching an image to show you what it looks like. 

I also tried `compose_email` with a few different options and they all result in something similar. What could be going wrong? It could be Outlook on my end that isn't rendering it properly but I wasn't sure where the problem was. Thanks again! 

![image](https://user-images.githubusercontent.com/14917555/67833405-a23a9780-fb38-11e9-8c82-cf44511dcd6e.png)

**Comment by rich-iannone** [comment] 2019-10-30 06:23
First of all, thanks for doing this testing! A report like this really helps us see where the weaknesses in the MIME message generation are.

We will have a look at this soon. My guess is that it’s an escaping issue with quoted-printable.

**Comment by rich-iannone** [comment] 2019-10-30 15:25
@kaushiklakshman Also, what version of Outlook? I just tested with Version 1909 (the latest) on Windows 10 and I got this:

<img width="1322" alt="win10_outlook_test_message" src="https://user-images.githubusercontent.com/5612024/67871887-7b17a200-fb07-11e9-8933-2ece63ce311f.png">

Would you be able to produce the text of the MIME message for me? That can be done with:

```r
test_message %>%
  blastula::generate_rfc2822() %>%
  cat(file = "mime.txt")
```

Then, the file could be attached here.

**Comment by rich-iannone** [comment] 2019-10-30 16:08
@kaushiklakshman So it I think I found the problem (and the fix is in the latest version of the branch). The problem was the doubled curly braces in the email template (`blastula:::bls_template()`). This was necessary when **glue** was used internally but it's not necessary now (and I think this has always been problematic for Outlook).

The template has been updated now and I tested locally on my machine. Could you test this again on yours? (I would really appreciate that.)

**Comment by kaushiklakshman** [comment] 2019-10-30 23:31
@rich-iannone thanks for looking at it so quickly. 

I reinstalled the package from the branch, however the issue seems to persist. My outlook version number is also 1909 and on Windows 10. 

The only difference now is I do see single `{` instead of `{{` that is in the screenshot attached previously. 

Unfortunately I am unable to execute your code that extracts the text of the MIME because the `blastula::generate_rfc2822` does not seem to be exported and available to run like that.  I tried cheating and copied the source code into a function in my environment but it breaks a lot because of other dependencies.  

Is there anything else I can do to help debug? Thanks again!

**Comment by rich-iannone** [comment] 2019-10-31 02:11
I actually made a typo in my last response (a pretty serious one!). You can use:

```r
test_message %>%
  blastula:::generate_rfc2822() %>%
  cat(file = "mime.txt")
```

which has three colons to access the unexported function. Could you try once more?

**Comment by kaushiklakshman** [comment] 2019-10-31 02:17
Ah so that's what the triple colon does! Attached the `mime.txt` output with this message 
[mime.txt](https://github.com/rich-iannone/blastula/files/3791862/mime.txt)

**Comment by rich-iannone** [comment] 2019-10-31 02:26
Thanks. I compared both (just trying to seeing what the difference is here) and yours has extra newlines in the first two headers. Here is the top of my `mime.txt`:

```
MIME-Version: 1.0
Date: Wed, 30 Oct 2019 22:19:31 -0400
Message-ID: <709afcbe-a0b4-466b-beb8-e995611aa077@blastula.local>
Content-Type: multipart/related; boundary="809926f9-30a1-48e1-aa20-e964386240be"

--809926f9-30a1-48e1-aa20-e964386240be
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!doctype html>
<html>
...
```

Yours starts like this:

```
MIME-Version: 1.0

Date: Thu, 31 Oct 2019 13:15:56 +1100

Message-ID: <5f141ad4-fb84-11e9-b17a-7bf181e43241@blastula.local>

Content-Type: multipart/related; boundary="5f1441b2-fb84-11e9-b17a-7bf181e43241"



--5f1441b2-fb84-11e9-b17a-7bf181e43241

Content-Type: text/html; charset=utf-8

Content-Transfer-Encoding: quoted-printable



<!doctype html>
<html>
...
```

I'll test this on my Windows VM to see if there is something significant here. If you send the email to a *different* client (e.g., a webmail client or phone email) do you get the same result?

**Comment by kaushiklakshman** [comment] 2019-10-31 02:35
Yes unfortunately same result on other webmail clients and phone (still outlook). 

I can't seem to send to a domain outside my org however if that's what you meant. I think it might be my org's mail server I get a `Error in curl_fetch_memory(url, handle = h) : RCPT failed: 550` error in that case.

**Comment by rich-iannone** [comment] 2019-10-31 02:39
Hmmm. Okay, this is interesting (and again, sorry that this doesn't work). I'll have a closer look at this tomorrow and try to come up with a solution (or at least understand the root cause).

**Comment by kaushiklakshman** [comment] 2019-10-31 02:43
Thanks very much for looking into it

**Comment by jcheng5** [comment] 2019-10-31 03:54
The extra line breaks are a red herring--it's a consequence of taking string data that contains `\r\n` line breaks (which `generate_rfc2822()` returns) and writing them using a text-mode connection (which `cat` does). R (for Windows only) thinks it's helping by automatically converting `\n` to `\r\n`, which in this case results in `\r\r\n`.

You can see this here:

```
> "1\r\n2"
[1] "1\r\n2"
> capture.output(cat("1\r\n2"))
[1] "1\r" "2"  
```

On Mac or Linux, these two expressions would return identical results.

**Comment by rich-iannone** [comment] 2019-10-31 04:07
Got it. Thanks Joe. Okay, there is some other reason. 

Perhaps it might be helpful to get the raw message text in Outlook. It’s not that obvious how to do it though. I did it by viewing the message in a browser (Outlook offers that option), and obtaining the file by inspecting the file URI in the browser first. There might be an easier way but that worked for me.

**Comment by rich-iannone** [comment] 2019-10-31 04:33
@jcheng5 It's all media queries and those are allowed by most email clients. This article (https://litmus.com/blog/understanding-media-queries-in-html-email) provides some information, and, a compatibility table (that shows Outlook not having compatibility btw).

However, it works in my stock Outlook installation in Windows 10 and Mac. I wonder if there is some application-level setting that determines this?

**Comment by nalsha** [comment] 2019-11-07 12:25
> Hi,
> 
> Thanks very much for resolving #91. I installed the package as per your comments on #87 and it works perfectly. I am able to send emails but am now faced a different problem.
> 
> I'm doing nothing outside the examples provided
> 
> ```
> library(tidyverse)
> library(blastula)
> 
> test_message <- prepare_test_message()
> 
> test_message %>%
>   smtp_send(
>     to = "me@myorg.com.au",
>     from = "me@myorg.com.au",
>     subject = "Test Message",
>     credentials = creds(host = "mail.myorg.com.au",
>                         port = 25, 
>                         use_ssl = FALSE)
>   )
> ```
> 
> The preview in Rstudio looks perfectly fine, but when I actually send the email it ends up not rendering some CSS and looks really off.
> 
> I'm attaching an image to show you what it looks like.
> 
> I also tried `compose_email` with a few different options and they all result in something similar. What could be going wrong? It could be Outlook on my end that isn't rendering it properly but I wasn't sure where the problem was. Thanks again!
> 
> ![image](https://user-images.githubusercontent.com/14917555/67833405-a23a9780-fb38-11e9-8c82-cf44511dcd6e.png)

I am getting the same error. Also, the conditionally formatted table through gt is losing its color formats in the email.

**Comment by nalsha** [comment] 2019-11-08 08:53
@Aarleks I was also getting the same error, however, installing "curl" and "httr" fixed it for me. Give it a try.

**Comment by Aarleks** [comment] 2019-11-14 22:50
Screenshot reference to #98 of relevance to this issue:
![2019-11-15-094015_1920x1080_scrot](https://user-images.githubusercontent.com/8971186/68902737-38073100-078d-11ea-8c0c-5d98e399d92e.png)

**Comment by jpsnijder** [comment] 2019-11-24 20:01
Dear Rich, 

first of all; thank you for this package and function! 

Unfortunately, I am having the same issues as the people above. Here are my details:
I am sending from an office365 e-mail.
`create_smtp_creds_key(    
  id = "MYORG",    
  user = "me@myorg.edu",    
  host = "smtp.office365.com",    
  port = 123,   
  use_ssl = TRUE    
)`

The issue persist when sending to: 
- Windows 10 Mail app (outlook based)
- iPhone mail app
- Gmail web-based in chrome browser
- Hotmail (outlook based)
- And office365 web-based.

R and Rstudio are up to date. 
Packages are up to date. 
I have attached the MIME.txt
[mime.txt](https://github.com/rich-iannone/blastula/files/3884062/mime.txt)
I have attached two screenshots: 1) gmail and 2) outlook web-based.
![Gmail](https://user-images.githubusercontent.com/42057767/69500647-b8c2dd00-0eb1-11ea-8546-e2f36aeebabc.png)
![Office365](https://user-images.githubusercontent.com/42057767/69500650-ba8ca080-0eb1-11ea-9b4d-93ab4867ec21.png)

Doesn't this look like the problem isn't with the mail programs, but rather with the creation of the HTML/CSS during the `compose_email` function?

**Comment by Alternikaner** [comment] 2019-11-28 14:15
Hi,

Firstly, I want to join jpsnijder in thanking Rich et al for this package - it's exactly what I've been looking for!

I suspect the cause of the issue might not be what it seems. Outlook is perfectly capable (at least on my system) of rendering mails sent via gmail, which seems to suggest that the problem lies with the Office365 server's handling of what blastula passes its way.

Attached are html dumps of two mails -- the "Great sun + cloud" example and the default test message --  sent via gmail and an Office365 server respectively. 

The buggy Office365 ones seem to have had their html mangled in very similar ways, and I believe this is what's causing the issue.

[sun_gmail.txt](https://github.com/rich-iannone/blastula/files/3901870/sun_gmail.txt)
[sun_office.txt](https://github.com/rich-iannone/blastula/files/3901872/sun_office.txt)
[testmsg_gmail.txt](https://github.com/rich-iannone/blastula/files/3901873/testmsg_gmail.txt)
[testmsg_office.txt](https://github.com/rich-iannone/blastula/files/3901874/testmsg_office.txt)

**Comment by Alternikaner** [comment] 2019-12-10 06:08
Hi,

Not sure if this speaks to the issue or not, but switching the order of the meta tags (lines 5 and 6) in bls_template.r results in (seemingly) improved rendering at the cost of encoding issues on certain characters and a trailing "="

<img width="581" alt="TestMail" src="https://user-images.githubusercontent.com/7880662/70499775-899fa300-1b22-11ea-9d05-f11e917429b4.PNG">

[testmail.txt](https://github.com/rich-iannone/blastula/files/3943273/testmail.txt)

**Comment by jdbarillas** [comment] 2020-01-23 02:46
We've narrowed it down to [two](https://github.com/rich-iannone/blastula/blob/9998e41dca776eb4d35199f0f61ec48d8693f306/R/mime.R#L263) separate [lines](https://github.com/rich-iannone/blastula/blob/9998e41dca776eb4d35199f0f61ec48d8693f306/R/mime.R#L270) in `mime.R`. 

```
    } else if (cur_line_len + nchar(chunk) >= 76) {
      out("=\r\n") # HERE
      cur_line_len <- 0L
    }
    out(chunk)
    cur_line_len <- cur_line_len + nchar(chunk)
  }
  # Ensure that trailing spaces are not ignored
  out("=\r\n\r\n") # HERE
```

More precisely, it's the `'='` at the beginning of each call to `out()` in those lines. I don't know the relevancy of including them in the string, but removing it from each allows the email to be correctly displayed when fully encoded. 

There's a quick hack of removing the text within `email_qp` before the email is passed to `send_mail` [at this repo](https://github.com/OlgaShldrr/blastula), but I think looking at the two lines above would be better in the long-term.

**Comment by rich-iannone** [comment] 2020-01-23 03:00
@jdbarillas Thank you so much for investigating this getting the root cause! We will make a fix for this soon, unless you'd like to make a PR for this yourself.

**Closed** 2020-03-06 19:41 UTC
Labels: Difficulty: ② Intermediate, Effort: ② Medium, Priority: ♨︎ Critical, Type: ☹︎ Bug

**Comment by rich-iannone** [comment] 2020-04-09 17:27
@kaushiklakshman We made fixes for this issue but we'd like to make sure the fixes work on your system. Could you confirm, after updating to the latest version of `master`, that the issue is resolved? We would really appreciate this, thanks!

**Comment by kaushiklakshman** [comment] 2020-04-14 01:22
Thanks @rich-iannone 

Can confirm that I installed the latest version of `master` and the issue is indeed resolved.

**Comment by dwhdai** [comment] 2020-04-27 23:04
omg, this thread just saved me a night of pulling my hair out. I can also confirm `master` is working, you guys are amazing! Thank you @rich-iannone 😍

**Comment by rich-iannone** [comment] 2020-04-27 23:12
@dwhdai thanks so much for the confirmatory report on this! This bug was pretty hard to repro but I’m quite glad we got past this.

**Comment by shahria3** [comment] 2021-02-27 15:29
> @kaushiklakshman We made fixes for this issue but we'd like to make sure the fixes work on your system. Could you confirm, after updating to the latest version of `master`, that the issue is resolved? We would really appreciate this, thanks!

Hi Rich! Apologies for my ignorance - i couldn't find master package how would i go about in install it?

**Comment by shahria3** [comment] 2021-02-27 15:30
> @kaushiklakshman We made fixes for this issue but we'd like to make sure the fixes work on your system. Could you confirm, after updating to the latest version of `master`, that the issue is resolved? We would really appreciate this, thanks!

@rich-iannone Hi Rich! Apologies for my ignorance - i couldn't find master package how would i go about in install it?

**Comment by jcheng5** [comment] 2021-02-28 23:26
@shahria3 The issue should be resolved on CRAN, so if you `install.packages("blastula")` and restart R then try again, the issue should be fixed. If not, please file a new issue with details as to what you're seeing. Thanks!
