### ISSUE TITLE
The emails sent from Blastula 0.31 arrive with a long paragraph of code. 

### ISSUE THREAD

**Issue by apalacio10** [rich-iannone/blastula#140] opened 2020-01-15 03:55 UTC
![Captura de Pantalla 2020-01-14 a la(s) 10 55 22 p  m](https://user-images.githubusercontent.com/40868159/72403671-f9580d80-3720-11ea-964d-583234a4b45f.png)

**Comment by Alternikaner** [comment] 2020-01-17 07:20
Duplicate of #93

**Comment by rich-iannone** [comment] 2020-03-07 04:42
Now fixed by #153

**Closed by rich-iannone** 2020-03-07 04:42 UTC
Labels: Difficulty: ③ Advanced, Effort: ③ High, Priority: ♨︎ Critical, Type: ☹︎ Bug
